name: Check Extensibility

on:
  pull_request_target:
    paths:
      - 'environments/dev/**'
      - 'extensions/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Prepare extensions
        run: npm run prepare-extensibility-dev && git diff --name-only environments/dev extensions

      - name: Check for changes in extensions.yaml
        id: check-changes
        run: ./.github/scripts/check-extensions.sh
        
      - name: Comment on PR
        uses: actions/github-script@v6
        if: steps.check-changes.outputs.CHANGED == 'true'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'RUN COMMAND RENDER EXTENSIBILITY'
            })
